INSERT INTO "products" (
  "id",
  "ref",
  "name",
  "slug",
  "category",
  "color",
  "priceCents",
  "saleCents",
  "description",
  "sizes",
  "images",
  "stock",
  "popularityScore",
  "isActive",
  "createdAt",
  "updatedAt"
) VALUES (
  'product-fr-101',
  'FR-101',
  'WHITE BOOTCUT JEANS',
  'white-bootcut-jeans',
  'JEANS',
  'DIRTY WHITE',
  3000,
  NULL,
  'Dirty-white low-rise bootcut jeans with a fitted silhouette through the upper leg and a flared leg opening. Finished with a washed effect, panelled detailing and raw-edge hems. Available in sizes S–XXXL.',
  ARRAY['S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
  ARRAY[
    '/products/white-bootcut-jeans/01-front.png',
    '/products/white-bootcut-jeans/02-product.png',
    '/products/white-bootcut-jeans/03-back.png',
    '/products/white-bootcut-jeans/04-side.png',
    '/products/white-bootcut-jeans/05-detail.png'
  ],
  20,
  100,
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("ref") DO UPDATE SET
  "name" = EXCLUDED."name",
  "slug" = EXCLUDED."slug",
  "category" = EXCLUDED."category",
  "color" = EXCLUDED."color",
  "priceCents" = EXCLUDED."priceCents",
  "saleCents" = EXCLUDED."saleCents",
  "description" = EXCLUDED."description",
  "sizes" = EXCLUDED."sizes",
  "images" = EXCLUDED."images",
  "stock" = EXCLUDED."stock",
  "popularityScore" = EXCLUDED."popularityScore",
  "isActive" = EXCLUDED."isActive",
  "updatedAt" = CURRENT_TIMESTAMP;
